version: '3.9'

services:
  users-api:
    build:
        context: ./MicroserviceUsers
        dockerfile: Inno_Shop_User/Dockerfile
    container_name: inno_shop_users_api
    depends_on:
        - users-db
        - redis-users
    ports:
        - "7144:8080"         
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ConnectionStrings__DefaultConnection: "Host=users-db;Port=5432;Database=Inno_Shop;Username=postgres;Password=170573"
        ConnectionStrings__Redis: "redis-users:6379"
        Services__ProductsBaseUrl: "http://product-api:8080"
  product-api:
    build:
        context: ./MicroserviceProduct
        dockerfile: Inno_Shop_Product/Dockerfile
    container_name: inno_shop_products_api
    depends_on:
        - products-db
    ports:
         - "7237:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=products-db;Port=5432;Database=Inno_Shop_Product;Username=postgres;Password=170573"
      Services__ProductsBaseUrl: "http://product-api:8080"

  users-db:
    image: postgres:16
    container_name: inno_shop_users_db
    restart: always
    environment:
        POSTGRES_DB: "Inno_Shop"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "170573"
    ports:
        - "5432:5432"
    volumes:
        - users_pgdata:/var/lib/postgresql/data

  products-db:
    image: postgres:16
    container_name: inno_shop_products_db
    restart: always
    environment:
        POSTGRES_DB: "Inno_Shop_Product"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "170573"
    ports:
        - "5433:5432"
    volumes:
        - products_pgdata:/var/lib/postgresql/data

  redis-users:
    image: redis:7
    container_name: inno_shop_redis_users
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_users:/data


volumes:
    users_pgdata:
    redis_data_users:
    products_pgdata:

